### ISSUE TITLE
[Staging] In the "Ride Arrived" screen, the car type and license number doesn't appear (passenger side)

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#344]
In the "Ride Arrived" screen, the car type and license number don't appear (passenger side).
I haven't tested it in production.

<img width="297" alt="number" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/2e744bdd-d12b-48ae-a146-4519fce793d5">

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal 
If this was tested in the staging environment using the driver@ezla-test.com driver user, I assume this the cause of this issue is because the driver user was created manually by @maorohana-redis and he did not save the car type and license number on it.

The easiest solution for this would be to edit the driver user on the backoffice of the staging and fill out the missing data.

**Comment by OrleeTal** [comment]
OK Thanks for checking it.

**Comment by OrleeTal** [comment]
Not a bug, just a user not inserted correctly.
